// Δύο προφίλ διάταξης για το ίδιο περιεχόμενο:
// print = A4 για εκτύπωση, phone = στενή σελίδα για ανάγνωση σε iPhone/iPad.
export const MANUAL_PROFILES = {
  print: {
    id: 'print',
    fileName: 'SpotlightPOS-Service-Mode-Manual.pdf',
    pageW: 210,
    pageH: 297,
    margin: { l: 18, r: 18, t: 20, b: 22 },
    lineSpacing: 1.45,
    smallNoteColor: [122, 114, 142],
    chapterBadge: 10,
    stepCircleR: 3.6,
    notePad: 5,
    imageMaxH: 132,
    sizes: {
      body: 10.5,
      chapterTitle: 17,
      chapterSubtitle: 10.5,
      sectionTitle: 12.5,
      stepTitle: 11.2,
      stepBody: 10.2,
      stepNumber: 8.5,
      noteTitle: 10.5,
      noteBody: 10,
      noteSmall: 8.8,
      caption: 8.5,
      footer: 8.5,
      tocTitle: 20,
      tocRow: 10.5,
      link: 12,
    },
    cover: {
      logoBoxW: 132,
      logoBoxH: 40,
      logoBoxY: 60,
      logoH: 24,
      logoPadX: 16,
      titleY: 150,
      titleMaxW: 164,
      title: 28,
      subtitle: 15,
      subtitleLong: 11,
      note: 9.5,
      edition: 10.5,
      afterTitle: 5,
      afterSubtitle: 1.3,
      afterSubtitleLong: 3.4,
      afterNote: 1.5,
      afterEdition: 2.6,
      dividerHalf: 25,
    },
  },
  phone: {
    id: 'phone',
    fileName: 'SpotlightPOS-Service-Mode-Manual-Kinito.pdf',
    pageW: 105,
    pageH: 186,
    margin: { l: 10, r: 10, t: 14, b: 16 },
    lineSpacing: 1.5,
    smallNoteColor: [104, 96, 124],
    chapterBadge: 9,
    stepCircleR: 3.3,
    notePad: 4.5,
    imageMaxH: 120,
    sizes: {
      body: 11.5,
      chapterTitle: 19,
      chapterSubtitle: 11,
      sectionTitle: 13.5,
      stepTitle: 13,
      stepBody: 11.5,
      stepNumber: 9.5,
      noteTitle: 11.5,
      noteBody: 11.5,
      noteSmall: 10,
      caption: 9.5,
      footer: 9,
      tocTitle: 16,
      tocRow: 11,
      link: 13,
    },
    cover: {
      logoBoxW: 82,
      logoBoxH: 26,
      logoBoxY: 30,
      logoH: 14,
      logoPadX: 10,
      titleY: 95,
      titleMaxW: 77,
      title: 16,
      subtitle: 11,
      subtitleLong: 9,
      note: 8.5,
      edition: 9,
      afterTitle: 4,
      afterSubtitle: 2,
      afterSubtitleLong: 3.5,
      afterNote: 3,
      afterEdition: 4,
      dividerHalf: 16,
    },
  },
};